import re

file_path = "frontend/components/navigation.py"
with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# Remove the CSS for the hamburger wrapper and button
content = re.sub(r'/\* Eliminate vertical space for the wrapper \*/.*?/\* Hide native default multipage nav generated by Streamlit \*/', '/* Hide native default multipage nav generated by Streamlit */', content, flags=re.DOTALL)

# Remove the actual toggle button
content = re.sub(r'st\.button\("?", on_click=toggle_sidebar, key="sidebar_toggle_btn"\)', '', content)

with open(file_path, "w", encoding="utf-8") as f:
    f.write(content)
