import streamlit as st

def toggle_sidebar():
    st.session_state["sidebar_collapsed"] = not st.session_state.get("sidebar_collapsed", False)

def render_sidebar():
    # ----------------------------------------
    # GLOBAL THEME STATE
    # ----------------------------------------
    if "theme" not in st.session_state:
        st.session_state["theme"] = "light"
        
    if "sidebar_collapsed" not in st.session_state:
        st.session_state["sidebar_collapsed"] = False
    
    theme = st.session_state["theme"]
    collapsed = st.session_state["sidebar_collapsed"]

    # ----------------------------------------
    # DEFINE CSS BEFORE USING IT
    # ----------------------------------------
    css = ""

    # Provide safe fallback for CSS just in case
    if theme == "dark":
        css = f"""<style>
        /* DARK MODE SIDEBAR SPECIFIC OVERRIDES IF NEEDED */
        [data-testid="stSidebar"] {{
            background-color: #0B1324 !important;
        }}
        """
    else:
        css = f"""<style>
        /* LIGHT MODE SIDEBAR SPECIFIC OVERRIDES IF NEEDED */
        [data-testid="stSidebar"] {{
            background-color: #0B1930 !important;
        }}
        """

    # Add the structural CSS that doesn't change based on theme
    css += f"""
    /* Removed absolute positioning for hamburger button */

    /* AGGRESSIVELY HIDE NATIVE COLLAPSE CONTROLS */
    [data-testid="collapsedControl"],
    [data-testid="stSidebarCollapseButton"],
    [data-testid="stSidebarHeader"],
    button[title="Close sidebar"] {{
        display: none !important;
    }}

    /* Disable native scrollbar */
    [data-testid="stSidebar"] ::-webkit-scrollbar {{ display: none !important; }}

    /* Force our custom width onto the native sidebar */
    [data-testid="stSidebar"] {{
        width: {'0px' if collapsed else '290px'} !important;
        min-width: {'0px' if collapsed else '290px'} !important;
        max-width: {'0px' if collapsed else '290px'} !important;
        transition: width 0.3s ease;
        overflow-x: hidden;
        {'padding: 0 !important;' if collapsed else ''}
        {'border-right: none !important;' if collapsed else ''}
    }}

    /* Make sidebar text color consistent */
    [data-testid="stSidebar"] * {{
        color: #E2E8F0 !important;
        {'display: none !important;' if collapsed else ''}
    }}

    /* Push main content to the right depending on sidebar state */
    [data-testid="stSidebar"] + section {{
        margin-left: {'0px' if collapsed else '290px'} !important;
        transition: margin-left 0.3s ease;
    }}

    /* Hide native default multipage nav generated by Streamlit */
    [data-testid="stSidebarNav"] {{ display: none !important; }}

    /* Hide text labels natively when collapsed so only icons show */
    {'[data-testid="stSidebar"] p { display: none !important; }' if collapsed else ''}

    /* Custom Navigation Container Spacing */
    .custom-nav-container {{
        display: flex;
        flex-direction: column;
        gap: 4px;
        margin-top: -10px;
        padding-bottom: 80px;
    }}

    /* Custom styling for st.page_link */
    [data-testid="stSidebar"] [data-testid="stPageLink-NavLink"] {{
        background-color: transparent;
        color: #E2E8F0 !important;
        border-radius: 8px;
        margin: 2px 12px;
        padding: 8px 12px;
        text-decoration: none;
    }}
    [data-testid="stSidebar"] [data-testid="stPageLink-NavLink"] p {{
        white-space: nowrap !important;
        overflow: visible !important;
        text-overflow: clip !important;
    }}
    [data-testid="stSidebar"] [data-testid="stPageLink-NavLink"]:hover {{
        background-color: rgba(255,255,255,0.05);
    }}
    [data-testid="stSidebar"] [data-testid="stPageLink-NavLink"][data-active="true"],
    [data-testid="stSidebar"] [data-testid="stPageLink-NavLink"][aria-current="page"] {{
        background-color: #1E3A8A !important;
        font-weight: 600;
    }}

    /* Custom Logo */
    .custom-logo {{
        display: flex;
        align-items: center;
        gap: 12px;
        padding: {'0px' if collapsed else '44px 20px 24px 20px'};
        border-bottom: 1px solid rgba(255,255,255,0.05);
        font-size: 1.1rem;
        font-weight: 800;
        color: white;
        white-space: nowrap;
    }}
    .custom-logo-text {{
        {'display: none;' if collapsed else 'display: block; line-height: 1.3;'}
    }}

    /* Bottom User Section */
    .sidebar-bottom {{
        position: fixed;
        bottom: 0;
        left: 0;
        width: {'0px' if collapsed else '290px'};
        padding: {'0px' if collapsed else '16px 20px'};
        background-color: inherit;
        border-top: 1px solid rgba(255,255,255,0.05);
        display: flex;
        justify-content: space-between;
        align-items: center;
        color: #94A3B8;
        z-index: 100;
        transition: width 0.3s ease;
    }}
    .user-info {{
        display: flex;
        align-items: center;
        gap: 10px;
        font-size: 0.95rem;
    }}
    .user-info span {{
        {'display: none;' if collapsed else 'display: block; white-space: nowrap;'}
    }}
    .settings-icon {{
        {'display: none;' if collapsed else 'display: block;'}
    }}
    </style>
    """

    # ----------------------------------------
    # ONLY NOW USE css
    # ----------------------------------------
    st.markdown(css, unsafe_allow_html=True)
    
    # ----------------------------------------
    # SIDEBAR TOGGLE (Moved to header.py)
    # ----------------------------------------
    # (Hamburger button is now in header.py)

    # ----------------------------------------
    # SIDEBAR
    # ----------------------------------------
    with st.sidebar:
        # Logo
        st.markdown(f"""
        <div class="custom-logo">
            <span style="font-size: 1.5rem;">🏛️</span>
            <div class="custom-logo-text">Smart Loan<br>Risk & Approval<br>System</div>
        </div>
        """, unsafe_allow_html=True)
        
        # Navigation Links Container
        st.markdown('<div class="custom-nav-container">', unsafe_allow_html=True)
        
        # Streamlit native page_links
        st.page_link("pages/01_Home.py", label=" " if collapsed else "Home", icon="🏠")
        st.page_link("pages/02_Data_Upload.py", label=" " if collapsed else "Data Upload", icon="📥")
        st.page_link("pages/04_Data_Analysis.py", label=" " if collapsed else "Data Analysis", icon="📈")
        st.page_link("pages/05_Model_Training.py", label=" " if collapsed else "Model Training & Comparison", icon="🤖")
        st.page_link("pages/07_New_Applicant.py", label=" " if collapsed else "New Applicant", icon="👤")
        st.page_link("pages/08_Explainability.py", label=" " if collapsed else "Explainability", icon="🧠")
        st.page_link("pages/10_Reports.py", label=" " if collapsed else "Reports", icon="📄")
        
        st.markdown('</div>', unsafe_allow_html=True)

        # Admin Bottom
        st.markdown("""
        <div class="sidebar-bottom">
            <div class="user-info">
                <span>👤</span>
                <span>Admin User</span>
            </div>
            <span class="settings-icon">⚙️</span>
        </div>
        """, unsafe_allow_html=True)
